### ISSUE TITLE
The media could not be loaded

### ISSUE THREAD

**Issue by Discostu36** [unixfox/invidious-custom#20]
Videos can't be streamed anymore, I always get an error message.

![Screenshot_20220118-200727_1](https://user-images.githubusercontent.com/30999326/150002625-27594ca9-82b6-4b91-94e5-d75f32faf9f9.png)

**Comment by unixfox** [comment]
Oops sorry, it's fixed! Thanks for reporting.

**Comment by vlur** [comment]
I still get this error for every video in qutebrowser. Seems to work in Brave.

qutebrowser v2.4.0
Git commit: 
Backend: QtWebEngine 5.15.2, based on Chromium 87.0.4280.144
Qt: 5.15.2

**Comment by unixfox** [comment]
> I still get this error for every video in qutebrowser. Seems to work in Brave.
> 
> qutebrowser v2.4.0
> Git commit: 
> Backend: QtWebEngine 5.15.2, based on Chromium 87.0.4280.144
> Qt: 5.15.2

Is it vanilla qutebrowser or did you configure something? I would like to replicate the issue that's why.

**Comment by vlur** [comment]
I tried just now and videos play fine on invidious.snopyta.org, invidious.kavin.rocks, & vid.puffyan.us. yewtu.be still has the error.

>Is it vanilla qutebrowser or did you configure something? I would like to replicate the issue that's why.

I have keybinds for spawning mpv from hinted links (which is what I've been doing since this issue appeared for me anyway), Brave's Rust adblocker list, and some cosmetic changes, but nothing that would be altering the default functionality AFAIK.

**Comment by unixfox** [comment]
Can you show me the full steps you are doing for viewing on qutebrowser?
Maybe you could record that and send the video here?

Does qutebrowser have devtools? If so could you look at the requests done by the browser and make a screenshot of it?

**Comment by vlur** [comment]
`:devtools` will open the web inspector in qutebrowser. When I go to (for example's sake) https://yewtu.be/watch?v=7IaYSxDp88s and look at the Network tab, it looks like a request is first canceled and then being re-requested and blocked every second or so. That lines up with the error message "breathing" every second or so; I'll see a flash of the 'play' button in the center of the video before it's replaced with an 'x' and the error message again. This continues for as long as I have a video page open.

![qbdevtools01](https://user-images.githubusercontent.com/44228316/151658311-133f4b0a-3b72-4100-b1fe-eb2fbfae6552.png)

```
fetch("https://yewtu.be/latest_version?id=7IaYSxDp88s&itag=22", {
  "headers": {
    "accept": "*/*",
    "accept-language": "en-US,en;q=0.9",
    "range": "bytes=0-",
    "sec-fetch-dest": "video",
    "sec-fetch-mode": "no-cors",
    "sec-fetch-site": "same-origin"
  },
  "referrer": "https://yewtu.be/watch?v=7IaYSxDp88s",
  "referrerPolicy": "same-origin",
  "body": null,
  "method": "GET",
  "mode": "cors",
  "credentials": "include"
});
```
If I double-click any of the (blocked:csp) errors, the video starts playing alone in a new tab. Content security policy? Clearly I must have something misconfigured somehow, but I don't know what to look for.

**Comment by unixfox** [comment]
I've added two months ago the redirect to external servers (eu1.proxy.yewtu.be and eu2.proxy.yewtu.be) because I needed external servers for handling the insane amount of 1.5Gbps of bandwidth used by my users.

I thought that by modifying the CSP in order to allow the new external servers, this would work on most modern browsers, but it seems like no.

Thank you for the explanations, I'll try to see if I can fix the CSP for qutebrowser.

**Comment by vlur** [comment]
Enabling DASH in the yewtube preferences seems to have fixed it. It is still strange that on my laptop with all the .config folder's settings copied from my desktop, and "preferred video quality" set to non-DASH quality, videos load right up no problem. That makes me think it's something on my end rather than anything you did. Thank you for your help troubleshooting.

**Comment by unixfox** [comment]
Okay I just installed Qutebrowser on my ArchLinux machine and I can't reproduce the issue, that's strange. Are you sure you aren't running some extensions blocking the CSP?
Maybe you could try to reset your browser?

![image](https://user-images.githubusercontent.com/4016501/151659152-bdf68c10-f9dc-4bde-9562-eb5ad5b81d05.png)
