### ISSUE TITLE
Subscription videos not being removed after played

### ISSUE THREAD

**Issue by mdcarreira** [unixfox/invidious-custom#31]
This happened a couple months ago or around that.

Previously, after I watched a video of one of my subscriptions, it was removed from my subscriptions page. But now, even after I watch it, it remains under my subscriptions page.

Is this an intended change of behavior? Or is it a bug?

**Comment by unixfox** [comment]
I have never seen a video being removed from the subscriptions after watching it.

**Comment by mdcarreira** [comment]
Thanks for your reply @unixfox.

It was the default behavior a while back, and I really enjoyed it because there were only unwatched videos on my list. These are the settings that I use:
![image](https://user-images.githubusercontent.com/23055725/160017249-a3919000-6ba6-4974-b075-f31141c7dfed.png)

I was fiddling with the settings and it seems that enabling the "Enable watch history" option did the trick.

Thanks providing such a awesome tool for free! Is there any way I can donate with crypto to show some support?

Cheers and keep up the good work!

**Comment by unixfox** [comment]
I'm glad you found the way to enable it back :). Sorry, the watch history was disabled by default because it caused too many issues when everyone had it activated by default.

You can donate to yewtu.be here: https://yewtu.be/donate or if you want to donate to the original project (invidious): https://invidious.io/donate/
The difference is that donating to yewtu.be will help me in maintaining this service for the public and to the original project this will help in improving the Invidious project (features, bug fixes and more).
