### ISSUE TITLE
yewtu.be is down

### ISSUE THREAD

**Issue by pklion** [unixfox/invidious-custom#48]
Looks like yewtu.be is down for at least about one day, isn't it?

**Comment by unixfox** [comment]
yes I've issues with my provider. I'm actively trying to solve this issue.

**Comment by unixfox** [comment]
it's fixed! sorry for the downtime!

my provider suspended my server due to a DMCA request...

**Comment by drogga** [comment]
@unixfox Hi, I just found out that you are the owner\maintainer of the YEWTU.be site and I want to let you know for some time (days) now that when going to\writting the address in the URL bar on any browser I use, it pormpts me to DL something (I deny\block the request) and the site doesn't load, in order to, I have to type `https://` before \ in front of it, since I didn't bookmark-ed it, wasn't the case before this issue happened and it loaded without the header or whatever is called there. I don't actually understand the matter or the terms and this seems related, that's why I'm writing this here and not creating a new issue ticket..., apologies if this is not the place to do so, or if i'm mistaken.

BTW, if it's problematic, I will delete this comment - no problem and if you reply, please quote me ;)
