### ISSUE TITLE
issue with http redirect?

### ISSUE THREAD

**Issue by unixfox** [unixfox/invidious-custom#49]
> @unixfox Hi, I just found out that you are the owner\maintainer of the YEWTU.be site and I want to let you know for some time (days) now that when going to\writting the address in the URL bar on any browser I use, it pormpts me to DL something (I deny\block the request) and the site doesn't load, in order to, I have to type `https://` before \ in front of it, since I didn't bookmark-ed it, wasn't the case before this issue happened and it loaded without the header or whatever is called there. I don't actually understand the matter or the terms and this seems related, that's why I'm writing this here and not creating a new issue ticket..., apologies if this is not the place to do so, or if i'm mistaken.

BTW, if it's problematic, I will delete this comment - no problem and if you reply, please quote me ;)

_Originally posted by @drogga in https://github.com/unixfox/invidious-custom/issues/48#issuecomment-1369088071_

**Comment by unixfox** [comment]
@drogga what browser are you using?

**Comment by drogga** [comment]
Mainly Bromite, but also tried with Chrome (Android) and Edge & Chrome on Windows, I don't think the browser is the issue, unless it's only with Chromium based ones, but that doesn't make much sense, since it's wasn't an issue a few weeks ago...

**Comment by unixfox** [comment]
Strange I can't reproduce this issue on chrome on android with a blank session. Did you try to clear your cookies and data? Can you reproduce the issue in private mode?

Maybe you should try to record this and post it here so that I can try to better understand the issue.

**Comment by drogga** [comment]
The browser is completely clean, since I always browse in incognito and clean it every day (Advenced method > All time), just in case.

**Comment by drogga** [comment]
If I record it, the only thing you will see is the "Chrome needs storage access to download files." prompt pop-up dialog, with a "Continue" button o. it, since I didn't allowed the storage permission on purpose, so a screen record or a screenshot are basically pointless.

**Comment by drogga** [comment]
The browser is completely clean, since I always browse in incognito and clean it every day (Advanced method > All time), just in case.

No such issue when manually typing some of the other instances.

If I record it, the only thing you will see is the "Chrome needs storage access to download files." prompt pop-up dialog, with a "Continue" button on it, since I didn't allowed the storage permission on purpose, so a screen record or a screenshot are basically pointless.

Anyway, it turns out that it wants me to DL a 0.06 KB file...

It loads in the Samsung's "Internet" Browser, without the inclusion of "http://" or "https://".

**Comment by drogga** [comment]
Using WireGuard (VPNs) fixes the issue, tho it's a hit ot miss with the 1DM's Browser (I have it anyway, so I decided to try with it too).

**Comment by unixfox** [comment]
Are you sure you are not hardcoding the IP address of yewtu.be in your DNS servers or something?

**Comment by drogga** [comment]
Yes, I'm sure, since I am using https://dns.adguard-dns.com/dns-query in Bromite (just tried without it too, same outcome), but I haven't touched any DNS-es on the network, system-wide or in the other browsers, also tried with other devices, where no DNS are forced\changed, or a proxy(s) or a VPNs are running.

If it's a issue with the ISP, then we can't do anything, but then again, I tried on\in other locations with different devices and NET providers, still the same, so it's not that, and it's only since recently, so the anomaly is probably on your side...

**Comment by unixfox** [comment]
Can you try again? I think I found the issue.

**Comment by drogga** [comment]
Now it loads, it feels slower, but it loads, thanks.
If you don't mind sharing - what was the issue?
...I knew the problem wasn't on my side...

Can you please enable the "Discussions" Tab here ?, because I have some other thing(s) to report or  _complain_ about, but I don't want to create diff. issue tickets, unless you are ok with being mentioned in this one..., because I like to throw everything or at least multiple things in 1 (all-in-one), but most devs. are not ok with this.

**Comment by unixfox** [comment]
If it's issues to report then create issues. I don't mind.

**Comment by drogga** [comment]
> I don't mind.

OK then:
I was about to report that Some subscriptions's videos don't show up/get listed, but they actually take a really long time to show up, hours actually...

YT added the "Live" and "Shorts" tabs and delisted those from the "Videos" tab, none of the instances reflect that change and those videos don't show up unfortunately, unless you are subscribed to the channels that publish them (sometimes, even then they don't show up in your list), IDK if you can do something or if I should report this at you at all (since last I checked the orig. repo source code hasn't been updated for months, seems abandoned to me).

Can you please enable TLS 1.0/1.1 ?, so I can actually load your instance in really old devices and on old browsers, where any updating to a modern software isn't a option.

**Comment by unixfox** [comment]
For the subscriptions issue, unfortunately I can't do anything. Sometimes youtube servers won't send the notification in time that a video just got published.

You should create an issue on the official invidious issue tracker: https://github.com/iv-org/invidious/issues

For the second issue a fix is in work in progress: https://github.com/iv-org/invidious/pull/3419

And about the last question, no I won't enable outdated TLS versions, these are insecure and bad for security. If you want older TLS versions use another instance or setup your own invidious instance.

**Comment by drogga** [comment]
> For the subscriptions issue, unfortunately I can't do anything. Sometimes youtube servers won't send the notification in time that a video just got published.

The "SkyTube" app fetches them right away, so probably it does it differently, IDK if the method can be used in invidious.

I tested all of the listed instances couple of months ago and unfortunately all but 1 (Chinese pink\purple themed) are is with enabled old TLS vers., the rest are only v1.3, unfortunately it's not possible for me to setup my own server\instance, so OK, I understand, what confuses me is - why then if the old TLS vers., which according to so many are such a security concern (insecure), but big companies and sites are still allowing them on their sites, like Google and Amazon (imdb.com), but NVM, ignore that. There's actually a pretty good explanation on f-droid (https://f-droid.org/en/2022/12/22/third-audit-results.html) regarding that and they have a pretty good point. ;)

Anyway, I wish you all the best and I hope that the WIP thing gets resolved and merged as soon as possible and the "next page" button in channel's will be available once again in the near future (since it's currently missing from most, if not all the instances).
Thanks for everything, take care and bye.

That's from me, signing-off.

**Comment by unixfox** [comment]
> > For the subscriptions issue, unfortunately I can't do anything. Sometimes youtube servers won't send the notification in time that a video just got published.
> 
> The "SkyTube" app fetches them right away, so probably it does it differently, IDK if the method can be used in invidious.

Invidious has two methods for refreshing the subscriptions.

The first one is youtube servers ping the Invidious instance that a new video is available.

The second one, is the same method that skytube use, it's doing a request for all the subscribed channels to youtube servers and comparing if new videos are available.
This work great for a local app like skytube but not for a big invidious instance. For example my invidious instance have more than 200 000 channels to refresh, that takes at least 3 days to complete!

So you understand why it's not a difficult task to fix.
